site_name: Mkdocs Manuel G贸mez
site_url: https://manuelgom5.github.io/mi-proyecto
theme:
  name: material

nav:
  - Home: index.md
  - About: about.md
  - Actividad 2.1 - Instalaci贸n y configuraci贸n servidor Nginx: ./practica2-1/index.md
  - Actividad 2.2 - Autenticaci贸n en Nginx: ./practica2-2/index.md
  - Actividad 2.3 - Proxy inverso con Nginx: ./practica2-3/index.md
  - Actividad 2.4 - Balanceo de carga con proxy inverso en Nginx: ./practica2-4/index.md
  - Actividad 2.5 - Proxy inverso y balanceo de carga con SSL en NGINX: ./practica2-5/index.md

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
